config/routes.rb
Rails.application.routes.draw do

  root 'ideas#index'

  resources :ideas
  get 'about' => 'static_page#about'
  get 'random' => 'static_page#random'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :description, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Pagy::Backend
  
end

app/controllers/ideas_controller.rb
# app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @pagy, @ideas = pagy(Idea.order(created_at: :desc), items: 5)
  end

 def create
    @idea = Idea.create(idea_params)
    if @idea.valid?
      flash[:success] = "Your idea has been posted!"
    else
      flash[:alert] = "Woops! Looks like there has been an error!"
    end
    redirect_to root_path
  end

  def edit
    @idea = Idea.find(params[:id])
  end

   def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      flash[:success] = "The idea has been updated!"
      redirect_to root_path
    else
      flash[:alert] = "Woops! Looks like there has been an error!"
      redirect_to edit_idea_path(params[:id])
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    flash[:success] = "The idea was successfully deleted!"
    redirect_to root_path
  end

  private

  def idea_params
    params.require(:idea).permit(:description, :author)
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
    def about
    end
    def random
        @idea = Idea.all.sample
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
 include Pagy::Frontend
end

app/helpers/flash_messages_helper.rb
module FlashMessagesHelper
  def flash_wrapper_classes(type)
    if %w[alert danger].include?(type)
      'text-red-800 rounded-lg bg-red-50'
    elsif type == 'success'
      'text-green-800 rounded-lg bg-green-50'
    elsif type == 'warning'
      'text-yellow-800 rounded-lg bg-yellow-50'
    else
      'text-blue-800 rounded-lg bg-blue-50'
    end
  end

  def flash_button_classes(type)
    if %w[alert danger].include?(type)
      'bg-red-50 text-red-500 focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200'
    elsif type == 'success'
      'bg-green-50 text-green-500 focus:ring-2 focus:ring-green-400 p-1.5 hover:bg-green-200'
    elsif type == 'warning'
      'bg-yellow-50 text-yellow-500 focus:ring-2 focus:ring-yellow-400 p-1.5 hover:bg-yellow-200'
    else
      'bg-blue-50 text-blue-500 focus:ring-2 focus:ring-blue-400 p-1.5 hover:bg-blue-200'
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/ideas/edit.html.erb
<h1 class="text-3xl mb-5 font-bold">Revise Idea</h1>

<%= simple_form_for @idea, method: :patch , data: {  turbo: false } do |f| %>
  <%= f.input :description, input_html: { rows: 5, class: 'text-gray-800' } %>
  <%= f.input :author, input_html: { class: 'text-gray-800' } %>
  <%= f.submit 'Submit', class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800 mt-3' %>
<% end %>

app/views/ideas/index.html.erb
<div data-controller='modal' class="max-w-screen-xl mx-auto p-4">

  <!-- Add Idea Button -->
  <button data-modal-target="default-modal" data-modal-toggle="default-modal"
          class='text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-blue-800 shadow-lg shadow-cyan-500/50 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-6'>
    Add New Idea
  </button>

  <!-- Add Idea Modal -->
  <div id="default-modal" tabindex="-1" aria-hidden="true"
       class="hidden fixed inset-0 z-50 flex justify-center items-center overflow-auto">
    <div class="relative w-full max-w-2xl max-h-full p-4">
      <div class="bg-white rounded-lg shadow dark:bg-gray-700">
        <%= simple_form_for Idea.new, data: { turbo: false, action:"submit->modal#hideModal" } do |f| %>
          <div class="flex items-center justify-between p-4 border-b rounded-t">
            <h3 class="text-xl font-semibold text-gray-900 dark:text-white">Add New Idea</h3>
            <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 flex justify-center items-center"
                    data-modal-hide="default-modal">&times;</button>
          </div>
          <div class="p-4 space-y-4">
            <%= f.input :description, input_html: { rows: 5, class: 'text-gray-800' } %>
            <%= f.input :author, input_html: { class: 'text-gray-800' } %>
          </div>
          <div class="flex items-center justify-end p-4 border-t rounded-b">
            <%= f.submit 'Submit', class: 'text-white bg-blue-700 hover:bg-blue-800 px-5 py-2.5 rounded-lg' %>
            <button data-modal-hide="default-modal" type="button"
                    class="text-white bg-red-700 hover:bg-red-800 px-5 py-2.5 rounded-lg ml-2">
              Cancel
            </button>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- List of Ideas -->
  <% @ideas.each do |idea| %>
    <div class="rounded overflow-hidden shadow-lg mb-4 p-6 bg-white">
      <div class="font-bold text-xl mb-2"><%= idea.description %></div>
      <p class="text-sm text-gray-700 mb-4"><%= idea.author %></p>
      <div class="flex space-x-2">
        <%= button_to 'Delete', idea_path(idea), method: :delete, data: {  turbo: false },
            class: 'text-white bg-red-700 hover:bg-red-800 px-4 py-2 rounded-lg',
            form: { data: { turbo_confirm: "Are you sure?" } } %>
        <%= link_to 'Revise', edit_idea_path(idea),
            class: 'text-white bg-blue-700 hover:bg-blue-800 px-4 py-2 rounded-lg' %>
      </div>
    </div>
  <% end %>

  <!-- Pagy Pagination -->
  <div class="mt-6 flex justify-center">
    <% pagy_nav(@pagy, link_extra: 'class="page"') %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

       <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@300;400;600;700&family=Open+Sans:wght@300;400;600;700&family=Pacifico&display=swap" rel="stylesheet">


  </head>

  <body class="h-screen" >
  <%= render 'shared/nav' %>
   
    <div class="max-w-screen-xl mx-auto p-1 md:p-4">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
    </div>

 <%=render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="flash-message" data-controller="flash">
    <div class="flash flex items-center p-4 mx-2 md:mx-0 my-2 rounded-lg <%= flash_wrapper_classes(message_type) %>" role="alert">
      <div class="text-sm font-medium">
        <%= message %>
      </div>
      <button data-action="click->flash#dismiss" type="button" class="ml-auto -mx-1.5 -my-1.5 rounded-lg inline-flex items-center justify-center h-8 w-8 <%= flash_button_classes(message_type) %>" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
        </svg>
      </button>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
   <footer class="fixed bg-white bottom-0 w-full">
      <div class="max-w-screen-xl mx-auto p-1 md:p-4 text-center text-neutral-700 dark:text-neutral-200">
        <p>&copy; TECHBRAIN <%= Date.today.year %> All Rights Reserved</p>
      </div>
    </footer>

app/views/shared/_nav.html.erb
<nav class="bg-white border-gray-200">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-1 md:p-4">
    <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
      <span class="self-center text-2xl font-semibold whitespace-nowrap font-pacifico text-[30px] tracking-[2px] text-primary-500">Ideator</span>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-default" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white">
        <li>
          <a href="#" class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0" aria-current="page">All Ideas</a>
        </li>
        <li>
          <a href="/random" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0">Inspire Me</a>
        </li>
        <li>
          <a href="/about" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/static_page/about.html.erb
<h1 class="mb-5 text-4xl font-bold">About</h1>

<h4 class="mb-3 text-2xl font-bold">Share your ideas with the world and find others.</h4>

<p class="mb-3">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

<p class="mb-3">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

<p class="mb-3">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/static_page/random.html.erb
<% if @idea.present? %>
  <h1 class='mb-5 text-2xl font-bold'>Inspire Me</h1>

  <div class="rounded overflow-hidden shadow-lg">
    <div class="px-6 py-8 h-full">
      <div class="font-bold text-xl mb-2"><%= @idea.description %></div>
      <p class="text-sm text-gray-700"><%= @idea.author %> </p>
      <div class="mt-4">
        <%= link_to 'Delete', idea_path(@idea), method: :delete,
          class: 'text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 focus:outline-none dark:focus:ring-red-800',
          data: {confirm: "Are you sure?"} %>

        <%= link_to 'Revise', edit_idea_path(@idea),
          class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800' %>
      </div>
    </div>
  </div>
<% else %>
  <p>No ideas available to display.</p>
<% end %>